name: Deploy to Surge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run: surge ./build bestep.surge.sh --token ${{secrets.TOKEN}}
